#pragma once

#ifndef _RESOURCE_

#define _RESOURCE_

extern const TCHAR szAppName[];

#define MANIFEST "BesterChatServer.exe.manifest"

#define IDI_APP_ICON 1000

#define IDM_MAIN_MENU 101

#define IDM_FILE_NEW_GROUP 111
#define IDM_FILE_OPEN_GROUP 112
#define IDM_FILE_CLOSE_GROUP 113
#define IDM_FILE_SAVE_GROUP 114
#define IDM_FILE_SAVE_GROUP_AS 115
#define IDM_FILE_IMPORT 117
#define IDM_FILE_EXPORT 116
#define IDM_FILE_PRINT 117
#define IDM_FILE_EXIT 118

#define IDM_EDIT_CUT 121
#define IDM_EDIT_COPY 122
#define IDM_EDIT_PASTE 123
#define IDM_EDIT_DELETE 124
#define IDM_EDIT_PREFERENCES 125

#define IDM_GROUP_INFORMATION 131
#define IDM_GROUP_VIEW_USERS 132
#define IDM_GROUP_VIEW_MESSAGES 133
#define IDM_GROUP_VIEW_FILES 134
#define IDM_GROUP_VIEW_IMAGES 135
#define IDM_GROUP_SETTINGS 136

#define IDM_HELP_HELP 141
#define IDM_HELP_ABOUT 142

#endif
